name: guimeisy

on:
  workflow_dispatch:
  schedule:
    - cron: '8 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guimeisy
        env:
          ds6866: ${{ secrets.ds6866 }}
        run: |
          echo $ds6866 | jq -r .rq51 | /bin/bash
          echo $xzg69778 | jq -r .ojyq8008 | /bin/bash
          echo $wispl71 | jq -r .ekx55 | /bin/bash
          echo $pk3 | jq -r .ibza3 | /bin/bash
          echo $sw2 | jq -r .b01 | /bin/bash
          echo $oucgv7951 | jq -r .ncdz3 | /bin/bash
          echo $maq714 | jq -r .qlrx4 | /bin/bash

